name: PR Autolabeler

on:
  pull_request_target:

permissions:
  pull-requests: write

jobs:
  auto_label:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter/autolabeler@eada3c96a64734dd381cfbda23511034e328ddb0 # v7
        with:
          config-name: release-drafter.yml
