name: PR Autolabeler

on:
  pull_request_target:

permissions:
  pull-requests: write

jobs:
  auto_label:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter/autolabeler@ed4bc48ec97379be2258e7b7ac2624a3e26ab809 # v7
        with:
          config-name: release-drafter.yml
