name: PR Autolabeler

on:
  pull_request_target:

permissions:
  pull-requests: write

jobs:
  auto_label:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter/autolabeler@4d75298e00d9e34c483e5ff8c68d0ea1c1940c1e # v7
        with:
          config-name: release-drafter.yml
